name: Dockerfile Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Build Docker image
        run: docker build -t nginx .

      - name: Scan Dockerfile with Checkov
        run: docker run --rm -v ${{ github.workspace }}:/code bridgecrew/checkov --quiet -d /code -f Dockerfile
