name: Dockerfile Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: my-nginx

      - name: Scan Dockerfile with Checkov
        run: docker run --rm -v ${{ github.workspace }}:/code bridgecrew/checkov --quiet -d /code -f Dockerfile
