name: Dockerfile Scan

on:
  push:
    branches:
      - masster
  pull_request:
    branches:
      - master

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Scan Dockerfile with Checkov
        run: docker run --rm -v ${{ github.workspace }}:/code bridgecrew/checkov --quiet -d /code -f Dockerfile
